// Edit this file to adapt the NAIDOC classroom game.
// Keep sacred/secret knowledge out of this public classroom activity, and replace
// placeholder local content only after checking appropriate school/community guidance.

export const NAIDOC_EXPLORATION_STORAGE_KEY = 'archaeologyDigApp:naidocExploration:v1';

export const NAIDOC_EXPLORATION_TITLE = '50 Years of Deadly: Culture, Country and Discovery';

export const NAIDOC_EXPLORATION_AREAS = [
  {
    id: 'welcome',
    title: 'Welcome: 50 Years of Deadly',
    shortTitle: 'Welcome',
    start: 0,
    end: 980,
    sky: '#a8d8cf',
    ground: '#6b7f4f',
    finalArea: false,
    teacherPace: '5 minutes',
  },
  {
    id: 'archaeology',
    title: 'Ancient Australia & Archaeology',
    shortTitle: 'Archaeology',
    start: 980,
    end: 2200,
    sky: '#b8d8ea',
    ground: '#9a7147',
    finalArea: false,
    teacherPace: '10 minutes',
  },
  {
    id: 'pondi',
    title: 'Pondi and the River Story',
    shortTitle: 'Pondi',
    start: 2200,
    end: 3380,
    sky: '#9ecbd3',
    ground: '#55796b',
    finalArea: false,
    teacherPace: '10 minutes',
  },
  {
    id: 'country',
    title: 'Culture, Country and Knowledge',
    shortTitle: 'Country',
    start: 3380,
    end: 4550,
    sky: '#b7d7b5',
    ground: '#6f7f45',
    finalArea: false,
    teacherPace: '10 minutes',
  },
  {
    id: 'milestones',
    title: 'NAIDOC Milestones',
    shortTitle: 'Milestones',
    start: 4550,
    end: 6020,
    sky: '#e0c58d',
    ground: '#855b40',
    finalArea: false,
    teacherPace: '10 minutes',
  },
  {
    id: 'final',
    title: 'Final Reflection & Quiz',
    shortTitle: 'Quiz',
    start: 6020,
    end: 6900,
    sky: '#a9c5d8',
    ground: '#4c6f62',
    finalArea: true,
    teacherPace: '10-15 minutes',
  },
];

export const NAIDOC_EXPLORATION_MARKERS = [
  {
    id: 'theme-50-years',
    areaId: 'welcome',
    x: 260,
    label: '50 Years of Deadly',
    tokenLabel: 'Theme token',
    required: true,
    cardTitle: 'NAIDOC 2026 Theme',
    cardText: 'The 2026 NAIDOC theme is "50 Years of Deadly". It celebrates 50 years of NAIDOC Week as a national moment of strength, culture and community.',
    classroomPrompt: 'What can the word "deadly" mean as a positive expression in many Aboriginal and Torres Strait Islander communities?',
  },
  {
    id: 'respectful-learning',
    areaId: 'welcome',
    x: 640,
    label: 'Respectful Learning',
    tokenLabel: 'Respect token',
    required: true,
    cardTitle: 'How We Learn Here',
    cardText: 'This game uses public, classroom-safe information. It does not include sacred, secret or restricted cultural knowledge.',
    classroomPrompt: 'Why is it important to say when content is a placeholder or needs local checking?',
  },
  {
    id: 'archaeology-evidence',
    areaId: 'archaeology',
    x: 1160,
    label: 'Evidence',
    tokenLabel: 'Evidence token',
    required: true,
    cardTitle: 'Archaeology Uses Evidence',
    cardText: 'Archaeologists study material evidence such as artefacts, sites, layers, tools, marks and landscape clues to understand the past.',
    classroomPrompt: 'Name one kind of evidence an archaeologist might record before removing anything.',
  },
  {
    id: 'heritage-preservation',
    areaId: 'archaeology',
    x: 1510,
    label: 'Preservation',
    tokenLabel: 'Care token',
    required: true,
    cardTitle: 'Heritage and Preservation',
    cardText: 'Heritage places and objects should be recorded and protected carefully because they can hold cultural, historical and scientific value.',
    classroomPrompt: 'Why can rushing or moving an object without recording it damage what we know?',
  },
  {
    id: 'ancient-australia',
    areaId: 'archaeology',
    x: 1900,
    label: 'Ancient Australia',
    tokenLabel: 'Deep time token',
    required: true,
    cardTitle: 'Deep Time on this Continent',
    cardText: 'Australia has very deep human histories. Archaeological evidence helps students understand long connections between people, place and environment.',
    classroomPrompt: 'How is "deep time" different from only studying recent events?',
  },
  {
    id: 'pondi-placeholder',
    areaId: 'pondi',
    x: 2380,
    label: 'Pondi Story',
    tokenLabel: 'Story token',
    required: true,
    cardTitle: 'Pondi / Murray Cod Story Placeholder',
    cardText: 'Placeholder: Pondi, the giant Murray Cod, is connected with river stories in parts of the Murray River region. This interaction should be checked and adapted with appropriate local guidance.',
    classroomPrompt: 'Why should a local story be treated as a story with meaning, not just a quiz fact?',
  },
  {
    id: 'river-country',
    areaId: 'pondi',
    x: 2780,
    label: 'River Country',
    tokenLabel: 'River token',
    required: true,
    cardTitle: 'River, Country and Memory',
    cardText: 'River stories can connect people, places, animals, movement and responsibilities. Country is not just scenery; it can hold relationships and knowledge.',
    classroomPrompt: 'What changes when we think of a river as part of Country rather than just a waterway?',
  },
  {
    id: 'story-respect',
    areaId: 'pondi',
    x: 3160,
    label: 'Story Respect',
    tokenLabel: 'Respectful story token',
    required: true,
    cardTitle: 'Story-Based Interaction',
    cardText: 'This stop asks students to listen for meaning and context. It avoids turning cultural story into a simple "right or wrong" trivia item.',
    classroomPrompt: 'What is one respectful way to discuss a story from another culture?',
  },
  {
    id: 'local-placeholder',
    areaId: 'country',
    x: 3560,
    label: 'Local Placeholder',
    tokenLabel: 'Local edit token',
    required: true,
    cardTitle: 'Local Knowledge Placeholder',
    cardText: 'Replace this card with the local language group, Country, river/place names and school-approved wording for your area.',
    classroomPrompt: 'What local details should a teacher check before using this lesson?',
  },
  {
    id: 'country-knowledge',
    areaId: 'country',
    x: 3940,
    label: 'Country',
    tokenLabel: 'Country token',
    required: true,
    cardTitle: 'Culture, Country and Knowledge',
    cardText: 'Cultural knowledge can include relationships with land, water, seasons, plants, animals, language, family and community responsibilities.',
    classroomPrompt: 'Why should cultural knowledge be presented with care and context?',
  },
  {
    id: 'language-group',
    areaId: 'country',
    x: 4320,
    label: 'Language Group',
    tokenLabel: 'Language token',
    required: true,
    cardTitle: 'Language Group Placeholder',
    cardText: 'Placeholder: Add the relevant local language group name only after checking the correct spelling, pronunciation guidance and classroom permissions.',
    classroomPrompt: 'Why can spelling and pronunciation matter when learning local names?',
  },
  {
    id: 'milestone-1970s',
    areaId: 'milestones',
    x: 4720,
    label: '1970s',
    tokenLabel: '1970s token',
    required: true,
    cardTitle: 'From Local Action to National Recognition',
    cardText: 'The last 50 years of NAIDOC history show how community action, advocacy and celebration grew into a major national week of recognition.',
    classroomPrompt: 'What is one reason public recognition can matter?',
  },
  {
    id: 'milestone-celebration',
    areaId: 'milestones',
    x: 4960,
    label: 'Celebration',
    tokenLabel: 'Celebration token',
    required: false,
    cardTitle: 'Celebrating Excellence',
    cardText: 'NAIDOC Week celebrates Aboriginal and Torres Strait Islander histories, cultures, achievements and continuing contributions.',
    classroomPrompt: 'What kinds of achievements might a community choose to celebrate?',
  },
  {
    id: 'milestone-schools',
    areaId: 'milestones',
    x: 5200,
    label: 'Schools',
    tokenLabel: 'Learning token',
    required: true,
    cardTitle: 'Learning in Schools',
    cardText: 'Schools can use NAIDOC Week to learn with respect, update old assumptions and include Aboriginal and Torres Strait Islander perspectives.',
    classroomPrompt: 'What makes a classroom activity respectful instead of tokenistic?',
  },
  {
    id: 'milestone-community',
    areaId: 'milestones',
    x: 5440,
    label: 'Community',
    tokenLabel: 'Community token',
    required: false,
    cardTitle: 'Community-Led Meaning',
    cardText: 'NAIDOC activities are strongest when they listen to community voices and avoid treating culture as decoration.',
    classroomPrompt: 'How could a school make sure an activity is connected to community voices?',
  },
  {
    id: 'milestone-today',
    areaId: 'milestones',
    x: 5680,
    label: 'Today',
    tokenLabel: 'Today token',
    required: true,
    cardTitle: '50 Years of Deadly Today',
    cardText: 'The 2026 theme invites students to look back at 50 years of strength while also thinking about the present and future.',
    classroomPrompt: 'What is one question you still have about culture, Country or NAIDOC?',
  },
  {
    id: 'final-gathering',
    areaId: 'final',
    x: 6320,
    label: 'Reflection Circle',
    tokenLabel: 'Reflection token',
    required: false,
    cardTitle: 'Ready for Reflection',
    cardText: 'You have gathered the required knowledge pieces. The final quiz checks only information shown in the game.',
    classroomPrompt: 'What is one thing you learned about culture, Country or NAIDOC?',
  },
];

export const NAIDOC_EXPLORATION_QUIZ = [
  {
    id: 'quiz-theme',
    sourceMarkerId: 'theme-50-years',
    question: 'What is the 2026 NAIDOC theme used in this game?',
    options: ['50 Years of Deadly', 'Ancient Tools Only', 'River Quiz Challenge', 'Museum Race'],
    correctIndex: 0,
  },
  {
    id: 'quiz-safe-content',
    sourceMarkerId: 'respectful-learning',
    question: 'What kind of knowledge does this classroom game avoid using?',
    options: ['Public information', 'Sacred, secret or restricted knowledge', 'Teacher pacing notes', 'Quiz questions'],
    correctIndex: 1,
  },
  {
    id: 'quiz-evidence',
    sourceMarkerId: 'archaeology-evidence',
    question: 'Which of these is an example of material evidence?',
    options: ['A random guess', 'An artefact or site layer', 'A scoreboard', 'A made-up shortcut'],
    correctIndex: 1,
  },
  {
    id: 'quiz-preservation',
    sourceMarkerId: 'heritage-preservation',
    question: 'Why should heritage objects and places be recorded carefully?',
    options: ['To protect cultural, historical and scientific value', 'To make the game harder', 'To hide them from students', 'To turn them into points'],
    correctIndex: 0,
  },
  {
    id: 'quiz-deep-time',
    sourceMarkerId: 'ancient-australia',
    question: 'What does deep time help students think about?',
    options: ['Only events from this week', 'Very long human histories and connections', 'The fastest route through a level', 'Only written records'],
    correctIndex: 1,
  },
  {
    id: 'quiz-story',
    sourceMarkerId: 'pondi-placeholder',
    question: 'How should the Pondi / Murray Cod content be treated in this first version?',
    options: ['As a combat challenge', 'As a checked and respectful story placeholder', 'As secret knowledge', 'As a joke answer'],
    correctIndex: 1,
  },
  {
    id: 'quiz-country',
    sourceMarkerId: 'river-country',
    question: 'What idea does the river Country card teach?',
    options: ['Country is only scenery', 'Country can hold relationships and knowledge', 'Rivers only matter for travel', 'Stories should be skipped'],
    correctIndex: 1,
  },
  {
    id: 'quiz-local',
    sourceMarkerId: 'local-placeholder',
    question: 'What should be replaced with locally checked information?',
    options: ['The keyboard controls', 'The local language group, Country and place names', 'The browser', 'The quiz button color'],
    correctIndex: 1,
  },
  {
    id: 'quiz-schools',
    sourceMarkerId: 'milestone-schools',
    question: 'What can schools use NAIDOC Week to do?',
    options: ['Learn with respect and update old assumptions', 'Avoid all discussion', 'Score culture as points', 'Replace local voices'],
    correctIndex: 0,
  },
  {
    id: 'quiz-today',
    sourceMarkerId: 'milestone-today',
    question: 'What does the 2026 theme invite students to think about?',
    options: ['Only the past', 'The past, present and future', 'Only archaeology tools', 'Only the final score'],
    correctIndex: 1,
  },
];

export const getNaidocExplorationProgress = (collectedMarkerIds = new Set()) => {
  const collectedSet = collectedMarkerIds instanceof Set
    ? collectedMarkerIds
    : new Set(collectedMarkerIds);
  const requiredMarkers = NAIDOC_EXPLORATION_MARKERS.filter((marker) => marker.required);
  const requiredCollected = requiredMarkers.filter((marker) => collectedSet.has(marker.id)).length;

  return {
    requiredCollected,
    requiredTotal: requiredMarkers.length,
    finalUnlocked: requiredCollected === requiredMarkers.length,
  };
};

export const getNaidocAreaForX = (x) => (
  NAIDOC_EXPLORATION_AREAS.find((area) => x >= area.start && x < area.end)
  || NAIDOC_EXPLORATION_AREAS[NAIDOC_EXPLORATION_AREAS.length - 1]
);
