const journeyPropBlendOverrides = {
  room: 'desert-entry',
  props: [
    // Fake-bury polish layer: these values intentionally use zIndex/contact strips
    // because several imported props do not respond well to alpha/bury controls.
    {
      id: 'desert-entry-premium-column-1',
      sectionId: 'desert-entry',
      y: 601,
      brightness: 0.7,
      colorGradeFilter: 'saturate(72%) sepia(30%) contrast(82%) hue-rotate(6deg)',
      shadowOpacity: 0.24,
      shadowWidth: 230,
      shadowHeight: 26,
      sandOverlapHeight: 0,
      sandMoundWidth: 0,
      sandMoundHeight: 0,
      groundPebbles: 0,
      depth: 'foreground-occluder',
      layer: 'route-edge',
      zIndex: 2,
    },
    {
      id: 'desert-entry-premium-pillar-caps-1',
      sectionId: 'desert-entry',
      y: 617,
      brightness: 0.78,
      colorGradeFilter: 'saturate(74%) sepia(22%) contrast(86%) hue-rotate(3deg)',
      shadowOpacity: 0.18,
      shadowWidth: 160,
      shadowHeight: 20,
      sandOverlapHeight: 0,
      sandMoundWidth: 0,
      sandMoundHeight: 0,
      depth: 'route-edge',
      layer: 'route-edge',
      zIndex: 3,
    },
    {
      id: 'desert-entry-wooden-crates-1',
      sectionId: 'desert-entry',
      y: 629,
      brightness: 0.68,
      colorGradeFilter: 'saturate(60%) sepia(28%) contrast(80%) hue-rotate(6deg)',
      shadowOpacity: 0.2,
      shadowWidth: 130,
      shadowHeight: 16,
      sandOverlapHeight: 0,
      sandMoundWidth: 0,
      sandMoundHeight: 0,
      groundPebbles: 0,
      depth: 'route-edge',
      layer: 'ruin-detail',
      zIndex: 2,
    },
    {
      id: 'desert-entry-damaged-jackal-statue-1',
      sectionId: 'desert-entry',
      y: 512,
      brightness: 0.7,
      colorGradeFilter: 'saturate(78%) sepia(38%) contrast(82%) hue-rotate(8deg)',
      shadowOpacity: 0.2,
      shadowWidth: 105,
      shadowHeight: 14,
      sandOverlapHeight: 0,
      sandMoundWidth: 0,
      sandMoundHeight: 0,
      groundPebbles: 0,
      depth: 'route-edge',
      layer: 'route-edge',
      zIndex: 2,
    },
    {
      id: 'desert-entry-old-baskets-1',
      sectionId: 'desert-entry',
      y: 600,
      brightness: 0.74,
      colorGradeFilter: 'saturate(66%) sepia(24%) contrast(82%) hue-rotate(4deg)',
      shadowOpacity: 0.14,
      shadowWidth: 110,
      shadowHeight: 14,
      sandOverlapHeight: 0,
      sandMoundWidth: 0,
      sandMoundHeight: 0,
      groundPebbles: 0,
      depth: 'route-edge',
      layer: 'route-edge',
      zIndex: 2,
    },
    {
      id: 'desert-entry-premium-rubble-mound-blend-1',
      sectionId: 'desert-entry',
      y: 599,
      brightness: 0.76,
      colorGradeFilter: 'saturate(68%) sepia(22%) contrast(82%) hue-rotate(5deg)',
      shadowOpacity: 0.08,
      shadowWidth: 150,
      shadowHeight: 12,
      sandOverlapHeight: 0,
      sandMoundWidth: 0,
      sandMoundHeight: 0,
      depth: 'background',
      layer: 'route-edge',
      zIndex: 1,
    },
    {
      id: 'desert-entry-fallen-lintel-1-copy-1',
      sectionId: 'desert-entry',
      y: 519,
      brightness: 0.78,
      colorGradeFilter: 'saturate(70%) sepia(20%) contrast(84%) hue-rotate(3deg)',
      shadowOpacity: 0.14,
      shadowWidth: 105,
      shadowHeight: 12,
      sandOverlapHeight: 0,
      sandMoundWidth: 0,
      sandMoundHeight: 0,
      zIndex: 2,
    },
    {
      id: 'desert-entry-right-prop-contact-shadow',
      sectionId: 'desert-entry',
      type: 'ground-contact-detail-prop',
      groundDetailAssetKey: 'premiumRubbleContactShadow',
      width: 520,
      height: 52,
      depth: 'foreground-occluder',
      layer: 'route-edge',
      x: 1598,
      y: 604,
      label: 'right prop cluster contact shadow',
      brightness: 0.82,
      colorGradeFilter: 'saturate(76%) sepia(30%) contrast(84%) hue-rotate(5deg)',
      shadowOpacity: 0,
      sandOverlapHeight: 0,
      groundPebbles: 0,
      zIndex: 3,
      groundContactLayer: [
        {
          assetKey: 'premiumRubbleContactShadow',
          layer: 'overlay',
          mode: 'stretch',
          alignY: 'bottom',
          xRatio: 0.5,
          widthRatio: 1,
          yOffset: -52,
          height: 52,
          alpha: 0.52,
          filter: 'sepia(22%) saturate(82%) brightness(70%) contrast(96%) hue-rotate(5deg)',
        },
      ],
    },
    {
      id: 'desert-entry-right-prop-sand-cover-strip',
      sectionId: 'desert-entry',
      type: 'ground-contact-detail-prop',
      groundDetailAssetKey: 'premiumLongSandLip',
      width: 610,
      height: 38,
      depth: 'foreground-occluder',
      layer: 'route-edge',
      x: 1570,
      y: 606,
      label: 'right prop cluster sand cover strip',
      brightness: 0.82,
      colorGradeFilter: 'saturate(76%) sepia(30%) contrast(84%) hue-rotate(5deg)',
      shadowOpacity: 0,
      sandOverlapHeight: 0,
      groundPebbles: 0,
      zIndex: 4,
      groundContactLayer: [
        {
          assetKey: 'premiumLongSandLip',
          layer: 'overlay',
          mode: 'stretch',
          alignY: 'bottom',
          xRatio: 0.5,
          widthRatio: 1,
          yOffset: -44,
          height: 44,
          alpha: 0.62,
          filter: 'sepia(28%) saturate(80%) brightness(88%) contrast(88%) hue-rotate(5deg)',
        },
      ],
    },
    {
      id: 'desert-entry-right-prop-stone-scatter-cover',
      sectionId: 'desert-entry',
      type: 'ground-contact-detail-prop',
      groundDetailAssetKey: 'premiumSmallStoneScatter',
      width: 410,
      height: 32,
      depth: 'foreground-occluder',
      layer: 'route-edge',
      x: 1648,
      y: 608,
      label: 'right prop cluster small stone cover',
      brightness: 0.78,
      colorGradeFilter: 'saturate(72%) sepia(24%) contrast(86%) hue-rotate(4deg)',
      shadowOpacity: 0,
      sandOverlapHeight: 0,
      groundPebbles: 0,
      zIndex: 5,
      groundContactLayer: [
        {
          assetKey: 'premiumSmallStoneScatter',
          layer: 'overlay',
          mode: 'stretch',
          alignY: 'bottom',
          xRatio: 0.5,
          widthRatio: 1,
          yOffset: -34,
          height: 34,
          alpha: 0.5,
          filter: 'sepia(24%) saturate(78%) brightness(86%) contrast(90%) hue-rotate(4deg)',
        },
      ],
    },
  ],
  deletedPropIds: [],
  platforms: [],
  deletedPlatformIds: [],
  hazards: [],
  deletedHazardIds: [],
  routeGates: [],
  routeGateDoorways: [],
  checkpoints: [],
  miniBosses: [],
};

export default journeyPropBlendOverrides;
