import { Wind, Droplets, AlertTriangle, Moon } from 'lucide-react';

export const CATEGORIES = [
  { id: 'objects', title: "Artefacts (Objects people made)" },
  { id: 'remains', title: "Ancient Remains (Human or animal)" },
  { id: 'structures', title: "Features (Places and structures)" },
  { id: 'environment', title: "Environmental Evidence" },
  { id: 'written', title: "Primary Evidence (Written or symbolic)" }
];

export const RANDOM_EVENTS = [
  {
    id: 'sandstorm',
    title: 'Incoming Sandstorm!',
    description: 'A massive sandstorm is approaching the dig site! Visibility is dropping fast.',
    icon: Wind,
    time: 90,
    dangerColor: '#E89E5D'
  },
  {
    id: 'flood',
    title: 'Flash Flood Warning!',
    description: 'Heavy rains in the mountains have triggered a flash flood! The water is rising.',
    icon: Droplets,
    time: 75,
    dangerColor: '#3b82f6'
  },
  {
    id: 'looters',
    title: 'Tomb Raiders Spotted!',
    description: 'Local authorities report that looters are heading our way. We have to leave before they arrive!',
    icon: AlertTriangle,
    time: 80,
    dangerColor: '#f59e0b'
  },
  {
    id: 'nightfall',
    title: 'Generator Failure!',
    description: 'The sun is setting and our power generator just died! We cannot excavate in the pitch black.',
    icon: Moon,
    time: 70,
    dangerColor: '#8b5cf6'
  }
];

export const SCENARIOS = [
  {
    id: 'egypt',
    name: 'The Desert River Valley',
    civilization: 'Ancient Egypt',
    historicalContext: 'The Nile Valley was home to one of history’s most enduring civilizations. Archaeologists rely on the extreme dryness of the desert to preserve organic materials like papyrus and textiles that would normally rot.',
    evidence: [
      { id: 'eg_1', name: "Canopic Jar", type: "objects", discoveryMethod: "Unearthed carefully in a subterranean tomb using small brushes.", clue: "A carved stone jar with an animal head lid.", question: "What is the most likely historical interpretation of this evidence?", options: ["It was a ceremonial container designed to preserve internal organs for the afterlife", "It served as a storage vessel for expensive imported oils and perfumes used in rituals", "It was a decorative household urn used to store the ashes of a common citizen", "It was a symbolic offering jar filled with sacred grains to ensure eternal food"], correct: 0, image: "/museum/egypt_canopic_jar.png", rationale: "Ancient Egyptians believed the body must be preserved for the soul (Ka) to recognize it. Internal organs were removed during mummification and stored in four dedicated canopic jars." },
      { id: 'eg_2', name: "Faience Amulet", type: "objects", discoveryMethod: "Found by sifting excavated sand through a fine mesh screen.", clue: "A bright blue glazed bead shaped like a beetle (scarab).", question: "What is the most likely historical interpretation of this evidence?", options: ["It was a protective magical token meant to guard the heart during final judgment", "It was a high-status piece of jewelry representing the owner's wealth and rank", "It was a coin used in the temple economy to pay for funerary services and prayers", "It was a children's toy placed in the tomb to provide comfort in the spirit world"], correct: 0 },
      { id: 'eg_3', name: "Bronze Mirror", type: "objects", discoveryMethod: "Found using a metal detector near a residential dig sector.", clue: "A polished disc of bronze with a decorated handle.", question: "What is the most likely historical interpretation of this evidence?", options: ["It was used by priests to reflect sunlight into the dark inner sanctums of temples", "It was a personal grooming tool indicating an emphasis on appearance and status", "It was a signaling device used by soldiers to communicate across long distances", "It was a ritual object used to capture and redirect the spirit during ceremonies"], correct: 1 },
      
      { id: 'eg_4', name: "Mummified Remains", type: "remains", discoveryMethod: "Discovered inside a sealed sarcophagus, examined via X-ray.", clue: "A human body preserved with salts and wrapped in linen.", question: "What is the most likely historical interpretation of this evidence?", options: ["They possessed advanced chemical knowledge for the preservation of human tissue", "They suffered from a specific disease that caused the skin to darken and harden", "They practiced ritual sacrifice of laborers to accompany kings into the afterlife", "They were naturally mummified by the extreme heat and dry air of the desert"], correct: 0, image: "/museum/egypt_mummy.png" },
      { id: 'eg_5', name: "Cat Skeleton", type: "remains", discoveryMethod: "Excavated from a dedicated animal cemetery using dental picks.", clue: "Bones of a feline, showing signs of ceremonial wrapping.", question: "What is the most likely historical interpretation of this evidence?", options: ["It served as a protective household guardian to ward off pests and evil spirits", "Cats were revered as earthly symbols of deities and were ritually preserved", "They specifically bred small predators to assist in military border defense", "They believed cats were the only animals capable of traveling to the spirit world"], correct: 1 },
      { id: 'eg_6', name: "Worn Human Teeth", type: "remains", discoveryMethod: "Extracted from a jawbone and analyzed under a microscope.", clue: "Human teeth that are heavily ground down and flattened.", question: "What is the most likely historical interpretation of this evidence?", options: ["They utilized their teeth as specialized tools for softening tough leather and skins", "Their diet included stone-ground bread which contained abrasive grit and desert sand", "They suffered from a genetic condition that caused premature enamel loss across the population", "They practiced ritual tooth sharpening to signify their status within the warrior class"], correct: 1 },

      { id: 'eg_7', name: "Mudbrick Wall", type: "structures", discoveryMethod: "Identified by a difference in soil color during a trench dig.", clue: "A thick wall made of sun-dried mud and straw.", question: "What is the most likely historical interpretation of this evidence?", options: ["They utilized local natural resources to create durable building materials", "These bricks were primarily used for decorative paving in temple courtyards", "They imported these materials from neighboring regions to build royal palaces", "It was a temporary marker used to map out the dimensions of larger stone walls"], correct: 0 },
      { id: 'eg_8', name: "Limestone Block", type: "structures", discoveryMethod: "Located using Ground-Penetrating Radar (GPR).", clue: "A massive, perfectly cut block weighing 2 tons.", question: "What is the most likely historical interpretation of this evidence?", options: ["It was a natural rock formation created by millions of years of pressure", "They developed advanced engineering, mathematics, and highly organized labor forces", "It served as a defensive barrier built to protect the city from seasonal flooding", "It was a symbolic marker used to record the boundary of a local farm"], correct: 1 },
      { id: 'eg_9', name: "Tomb Shaft", type: "structures", discoveryMethod: "Discovered by clearing rubble from a vertical tunnel.", clue: "A deep vertical pit leading to a sealed room.", question: "What is the most likely historical interpretation of this evidence?", options: ["They needed a cool subterranean space to hide from the extreme desert sun", "They created elaborate hidden structures to protect the deceased from tomb robbers", "It was a deep well used to access groundwater for the local temple community", "It served as a trash pit for disposing of waste from large-scale construction sites"], correct: 1 },

      { id: 'eg_10', name: "Flax Seeds", type: "environment", discoveryMethod: "Recovered using flotation (mixing soil in water until seeds float).", clue: "Preserved ancient seeds of the flax plant.", question: "What is the most likely historical interpretation of this evidence?", options: ["They cultivated specific river plants to weave essential linen clothing and sails", "They used these seeds as a primary form of currency for buying luxury goods", "These seeds were a major source of oil used exclusively for temple lamps", "They gathered wild grasses rather than farming them in organized agricultural fields"], correct: 0 },
      { id: 'eg_11', name: "Nile Silt Layer", type: "environment", discoveryMethod: "Sampled using a core drill to analyze soil stratigraphy.", clue: "A thick layer of dark, rich river mud deep underground.", question: "What is the most likely historical interpretation of this evidence?", options: ["A massive earthquake caused the ground to sink and fill with river mud", "Their society relied on the annual flooding of the river for fertile farmland", "They purposefully imported mud from other regions to build their cities", "It is evidence of a single catastrophic flood that destroyed the entire civilization"], correct: 1 },
      { id: 'eg_12', name: "Dried Papyrus Reeds", type: "environment", discoveryMethod: "Found preserved in the extremely dry, arid desert sand.", clue: "Stalks of a plant that grows in marshes.", question: "What is the most likely historical interpretation of this evidence?", options: ["They harvested river plants to create essential items like boats and baskets", "These plants were an invasive species that damaged the local river economy", "They used dried reeds as a primary building material for large-scale cities", "It was a rare medicinal herb used only by the most elite members of society"], correct: 0 },

      { id: 'eg_13', name: "Papyrus Scroll", type: "written", discoveryMethod: "Found inside a sealed ceramic jar, handled with cotton gloves.", clue: "A fragile sheet made of woven reeds, covered in ink.", question: "What is the most likely historical interpretation of this evidence?", options: ["They had a complex system for recording taxes, legal codes, and myths", "They used these sheets as decorative wall coverings for royal bedrooms", "They recorded inventory lists for trade with distant Mediterranean tribes", "It was a specialized map used by sailors to navigate the Red Sea coasts"], correct: 0 },
      { id: 'eg_14', name: "Hieroglyph Carving", type: "written", discoveryMethod: "Discovered on a ruined wall and documented using 3D laser scanning.", clue: "Symbols including eyes, birds, and snakes carved into stone.", question: "What is the most likely historical interpretation of this evidence?", options: ["These patterns were purely decorative and held no specific linguistic value", "They used complex symbolic writing for monumental or religious texts", "It was a secret military code used to hide plans from invading armies", "It was a primitive counting system used to track the number of livestock"], correct: 1, image: "/museum/egypt_hieroglyphs.png" },
      { id: 'eg_15', name: "Ostracon", type: "written", discoveryMethod: "Unearthed by hand trowel in an ancient garbage dump area.", clue: "A broken piece of pottery with quick ink notes scribbled on it.", question: "What is the most likely historical interpretation of this evidence?", options: ["Pottery shards were used as formal legal documents in high-court proceedings", "They were sacred artifacts used to cast lots during religious festivals", "Broken pottery served as affordable 'scrap paper' for everyday notes or lists", "They were used as tokens in a complex game played by elite temple priests"], correct: 2 }
    ]
  },
  {
    id: 'mungo',
    name: 'The Ancient Dry Lake',
    civilization: 'Indigenous Australia (Lake Mungo)',
    historicalContext: 'Lake Mungo has revealed evidence of human occupation dating back over 42,000 years, including some of the world’s earliest ritual cremations and ochre burials, proving a long and complex cultural history.',
    evidence: [
      { id: 'mg_1', name: "Silcrete Stone Tool", type: "objects", discoveryMethod: "Found on the surface after wind erosion exposed the soil layer.", clue: "A sharp stone that has been carefully chipped (knapped).", question: "What is the most likely historical interpretation of this evidence?", options: ["They possessed sophisticated knowledge of rock properties to create specialized cutting tools", "These stones were likely used as heavy weights for securing large animal-hide shelters", "They served as ritual tokens that were traded between distant social groups for ceremony", "These rocks were naturally fractured by tectonic pressure and extreme desert heat cycles"], correct: 0, image: "/museum/mungo_stone_tool.png" },
      { id: 'mg_2', name: "Grinding Stone", type: "objects", discoveryMethod: "Excavated using a trowel and mapped using a GPS grid.", clue: "A large, flat sandstone rock with a smooth, worn depression in the center.", question: "What is the most likely historical interpretation of this evidence?", options: ["It was a ceremonial seat used by elders during community gatherings and law-making", "They developed technology to systematically process local seeds and grains into flour", "This stone was used as a heavy-duty lid for protecting underground water storage pits", "It served as a specialized anvil for shaping imported metal tools and weapons"], correct: 1 },
      { id: 'mg_3', name: "Ochre Fragment", type: "objects", discoveryMethod: "Sieved from an ancient campsite layer.", clue: "A piece of soft, red, iron-rich rock with scratch marks.", question: "What is the most likely historical interpretation of this evidence?", options: ["This mineral was used as a high-temperature flux for smelting local copper and iron", "It was processed into pigment for artistic expression, ritual ceremony, or body paint", "They utilized these iron-rich rocks as a specialized medicinal supplement for health", "Ochre was a primary building material used to create durable, waterproof clay structures"], correct: 1 },

      { id: 'mg_4', name: "Ritual Burial Skeleton", type: "remains", discoveryMethod: "Discovered eroding from a dune; examined with absolute respect and consultation.", clue: "A human skeleton sprinkled heavily with red ochre powder.", question: "What is the most likely historical interpretation of this evidence?", options: ["The red color is the result of natural mineral oxidation occurring after the burial", "They practiced complex, compassionate burial rituals and held deep spiritual beliefs", "This individual was likely a victim of a violent regional conflict with a rival group", "The body was placed in this specific position to protect it from large scavengers"], correct: 1, image: "/museum/mungo_ochre_burial.png", rationale: "Mungo Man and Mungo Lady represent the oldest known ritual burials in the world. The use of ochre and specific positioning shows deep spiritual care and complex social structures dating back 42,000 years." },
      { id: 'mg_5', name: "Cremated Bones", type: "remains", discoveryMethod: "Analyzed using radiocarbon dating in a controlled laboratory.", clue: "Human bones that have been burnt, smashed, and buried.", question: "What is the most likely historical interpretation of this evidence?", options: ["This represents one of the world's earliest known examples of complex ritual cremation", "These remains were accidentally burned during a massive natural bushfire event", "They used fire as a practical method for reducing the size of remains for transport", "The damage was caused by a domestic fire that spread to a nearby sleeping shelter"], correct: 0 },
      { id: 'mg_6', name: "Megafauna Bone", type: "remains", discoveryMethod: "Unearthed carefully using brushes near an ancient shoreline.", clue: "A massive bone belonging to an extinct giant kangaroo.", question: "What is the most likely historical interpretation of this evidence?", options: ["They brought elephants to the desert", "These ancient people coexisted with and hunted giant extinct animals", "The bone is from a dinosaur", "They farmed giant kangaroos"], correct: 1 },

      { id: 'mg_7', name: "Ancient Hearth", type: "structures", discoveryMethod: "Discovered by identifying a circular patch of heat-baked clay.", clue: "A collection of burnt rocks arranged in a circle.", question: "What is the most likely historical interpretation of this evidence?", options: ["They utilized controlled fire pits for warmth, specialized cooking, and social gather", "This feature is a natural clearing caused by lightning strikes on dry vegetation", "It served as a temporary signal beacon to communicate with distant nomadic groups", "The rocks were heated to create steam for the purpose of softening wooden tools"], correct: 0 },
      { id: 'mg_8', name: "Fossilized Footprints", type: "structures", discoveryMethod: "Revealed by shifting sands and recorded with 3D photogrammetry.", clue: "Hardened mud showing tracks of people running together.", question: "What is the most likely historical interpretation of this evidence?", options: ["They were performing a coordinated ritual dance during a major community festival", "The prints provide a direct snapshot of group dynamics, hunting strategies, or movement", "These tracks represent a defensive retreat from a large-bodied predator in the region", "The markings were carved into the clay by later groups as a form of symbolic art"], correct: 1 },
      { id: 'mg_9', name: "Stone Fish Trap", type: "structures", discoveryMethod: "Identified using aerial drones during a low-water period.", clue: "A complex arrangement of rocks in a dry riverbed.", question: "What is the most likely historical interpretation of this evidence?", options: ["They engineered the river landscape to sustainably harvest essential aquatic food sources", "These rock formations are the result of natural river erosion and sediment movement", "The structures were built as defensive barriers to prevent the movement of rival groups", "They were used as foundation supports for temporary wooden bridges across the river"], correct: 0 },

      { id: 'mg_10', name: "Shell Midden", type: "environment", discoveryMethod: "Sampled using a test pit to analyze the layers of shells.", clue: "A massive mound of discarded freshwater mussel shells.", question: "What is the most likely historical interpretation of this evidence?", options: ["These shells were used as a specialized form of currency for regional trade networks", "The site was a long-term habitation area where they harvested and ate lake resources", "They collected these shells for the primary purpose of decorating their shelters", "The mound was created by an ancient high-tide event that deposited shells in one spot"], correct: 1 },
      { id: 'mg_11', name: "Emu Egg Shells", type: "environment", discoveryMethod: "Found in a hearth; dated using Optically Stimulated Luminescence (OSL).", clue: "Scorched fragments of a very large bird egg.", question: "What is the most likely historical interpretation of this evidence?", options: ["They specifically kept emus as domesticated livestock for a consistent food source", "They gathered seasonal wild resources and prepared them using controlled fires", "The shells were used as a specialized form of armor during regional conflicts", "They utilized these large shells as water containers for traveling long distances"], correct: 1 },
      { id: 'mg_12', name: "Lake Silt Layer", type: "environment", discoveryMethod: "Core drilling revealed layers of mud beneath the modern desert sand.", clue: "Soil that only forms at the bottom of a deep, freshwater lake.", question: "What is the most likely historical interpretation of this evidence?", options: ["This modern desert landscape was previously a lush and productive lake environment", "They imported massive amounts of lake mud from other regions to fertilize gardens", "The silt was deposited during a single catastrophic flood that lasted for many months", "They lived in specialized homes built on stilts above the surface of the ancient lake"], correct: 0 },

      { id: 'mg_13', name: "Hand Stencil Rock Art", type: "written", discoveryMethod: "Located in a rock shelter; analyzed using non-destructive spectral imaging.", clue: "An outline of a human hand blown onto rock with ochre.", question: "What is the most likely historical interpretation of this evidence?", options: ["They had a deep, enduring connection and symbolic claim to their ancestral land", "These marks were casual signatures left by travelers passing through the region", "It served as a primitive method for tracking the number of members in a group", "The stencils were used to teach children how to recognize human skeletal anatomy"], correct: 0, image: "/museum/mungo_hand_stencil.png" },
      { id: 'mg_14', name: "Carved Boab Nut", type: "written", discoveryMethod: "Recovered from a dry cave environment which preserved the organic material.", clue: "A nut shell intricately carved with geometric patterns.", question: "What is the most likely historical interpretation of this evidence?", options: ["These shells were used as specialized containers for carrying sacred river water", "The carvings were a form of ownership mark used to identify personal food sources", "They expressed complex artistic and cultural stories through portable objects", "They served as specialized tokens used in a complex game played during festivals"], correct: 2 },
      { id: 'mg_15', name: "Ceremonial Stone Arrangement", type: "written", discoveryMethod: "Mapped using precision GPS equipment across a wide area.", clue: "Large stones intentionally placed in a massive geometric pattern.", question: "What is the most likely historical interpretation of this evidence?", options: ["These stones were arranged by natural geological forces and erosion over centuries", "It served as a map, celestial calendar, or sacred ceremonial site for the community", "The structure was a defensive wall built to protect the camp from invading groups", "They were used as heavy weights to secure the edges of large animal-hide shelters"], correct: 1 }
    ]
  },
  {
    id: 'rome',
    name: 'The Mediterranean Empire',
    civilization: 'Ancient Rome',
    historicalContext: 'Roman archaeology often focuses on the massive urban infrastructure and military might of the empire. From lead pipes to monumental inscriptions, their material culture reflects a highly organized and literate society.',
    evidence: [
      { id: 'rm_1', name: "Bronze Sestertius", type: "objects", discoveryMethod: "Located using a metal detector in an ancient marketplace.", clue: "A coin stamped with the face of an Emperor.", question: "What is the most likely historical interpretation of this evidence?", options: ["These coins were primarily used as specialized protective amulets for traveling merchants", "They maintained a standardized monetary economy and centralized political propaganda", "They utilized bronze tokens to track the distribution of daily grain rations to the poor", "The coins were produced by local temples to facilitate the purchase of sacrificial animals"], correct: 1, image: "/museum/roman_coin.png" },
      { id: 'rm_2', name: "Gladius", type: "objects", discoveryMethod: "Excavated from a battlefield layer using careful troweling.", clue: "A short, iron sword designed for stabbing.", question: "What is the most likely historical interpretation of this evidence?", options: ["They relied on a highly organized, professional military force with standardized equipment", "This blade was a specialized tool used for the ritual slaughter of large livestock", "It served as a ceremonial status symbol carried only by high-ranking civilian magistrates", "The sword was designed for heavy agricultural work such as clearing dense Mediterranean brush"], correct: 0, image: "/museum/roman_gladius.png" },
      { id: 'rm_3', name: "Samian Ware", type: "objects", discoveryMethod: "Found in a rubbish pit; pieced back together in the lab.", clue: "High-quality, mass-produced glossy red pottery.", question: "What is the most likely historical interpretation of this evidence?", options: ["These vessels were used exclusively for storing sacred oils during major religious festivals", "The red color was intended to mimic the appearance of expensive imported copper containers", "They possessed advanced industrial-scale manufacturing and extensive maritime trade networks", "This pottery was a specialized luxury item produced only for the use of the Imperial family"], correct: 2 },

      { id: 'rm_4', name: "Gladiator Skull", type: "remains", discoveryMethod: "Uncovered in a specific cemetery outside the city walls.", clue: "A skull showing healed blunt-force trauma.", question: "What is the most likely historical interpretation of this evidence?", options: ["The injuries suggest this individual was a victim of a violent domestic accident", "Violent sporting entertainment and ritualized combat were significant cultural practices", "These marks indicate a successful surgical procedure to relieve pressure on the brain", "The trauma was likely caused by a heavy building collapse during a major earthquake"], correct: 1, image: "/museum/roman_skull.png", rationale: "Gladiatorial combat was a central part of Roman culture. Skeletal analysis often reveals healed wounds, suggesting that while the games were violent, some gladiators survived multiple bouts and received medical care." },
      { id: 'rm_5', name: "Cremation Urn Ashes", type: "remains", discoveryMethod: "Sieved from a ceramic pot found in a roadside tomb.", clue: "Burnt human bone fragments inside an inscribed jar.", question: "What is the most likely historical interpretation of this evidence?", options: ["The ashes were kept in homes to ensure the continued presence of ancestor spirits", "Cremation was a formalized burial practice accompanied by specific commemorative markers", "These remains belong to high-ranking officials who were honored with public pyres", "The jar was used to store salt and the presence of bone is a result of later contamination"], correct: 1 },
      { id: 'rm_6', name: "Lead Isotope Teeth", type: "remains", discoveryMethod: "Extracted and analyzed using mass spectrometry.", clue: "Teeth containing high levels of lead and minerals from a distant region.", question: "What is the most likely historical interpretation of this evidence?", options: ["This individual was a long-distance traveler who lived in a city with lead plumbing", "They utilized lead as a specialized flavoring agent in their daily food and wine", "The high lead levels are a result of natural mineral absorption from the local soil", "They worked in a specialized lead smelting facility located near their primary home"], correct: 0 },

      { id: 'rm_7', name: "Aqueduct Arch", type: "structures", discoveryMethod: "Surveyed above ground; structural integrity tested.", clue: "A massive stone bridge carrying a water channel.", question: "What is the most likely historical interpretation of this evidence?", options: ["The structure was a monumental gateway built to mark the entrance to a major city", "Sophisticated engineering provided reliable clean water to sustain large urban populations", "It served as a defensive wall designed to monitor the movement of nomadic groups", "The arches were built as a raised ceremonial platform for religious processions"], correct: 1 },
      { id: 'rm_8', name: "Hypocaust", type: "structures", discoveryMethod: "Excavated by digging a test trench below a mosaic floor.", clue: "A basement system of pillars to allow hot air to flow under a floor.", question: "What is the most likely historical interpretation of this evidence?", options: ["The pillars were designed to protect the building from frequent flooding and moisture", "They possessed advanced central heating technology used in elite homes and bathhouses", "This basement served as a specialized storage facility for perishable food items", "The space was used as a hidden escape tunnel for the residents during times of war"], correct: 1 },
      { id: 'rm_9', name: "Mosaic Floor", type: "structures", discoveryMethod: "Carefully uncovered using fine brushes and sponges to reveal colors.", clue: "A floor made of thousands of tiny colored stones.", question: "What is the most likely historical interpretation of this evidence?", options: ["Wealthy citizens invested significantly in elaborate interior art and symbolic design", "The floor was a specialized religious map used to guide initiates through rituals", "These stones were used to provide a non-slip surface for indoor athletic training", "They utilized the different colors of stone to track the movement of the sun and time"], correct: 0 },

      { id: 'rm_10', name: "Volcanic Ash Layer", type: "environment", discoveryMethod: "Identified in a stratigraphic profile cut.", clue: "A thick, sudden layer of pumice and ash covering the city.", question: "What is the most likely historical interpretation of this evidence?", options: ["The ash was a specialized building material imported for high-strength concrete", "A catastrophic natural disaster occurred that rapidly buried and preserved the site", "This layer represents the debris from a massive industrial-scale fire in the city", "The ash was used as a form of fertilizer for the surrounding agricultural gardens"], correct: 1 },
      { id: 'rm_11', name: "Olive Pits", type: "environment", discoveryMethod: "Recovered via flotation from an ancient sewer drain.", clue: "Thousands of discarded pits from olive fruits.", question: "What is the most likely historical interpretation of this evidence?", options: ["The pits were collected and used as a specialized form of fuel for domestic heating", "Olives and olive oil were foundational commodities in their daily diet and economy", "They utilized these hard pits as a primitive form of ammunition for regional defense", "The trees were grown primarily for their wood rather than for the fruit they produced"], correct: 1 },
      { id: 'rm_12', name: "Dormouse Bones", type: "environment", discoveryMethod: "Sieved from an ancient ceramic jar using a fine mesh.", clue: "Bones of small rodents found inside a specialized clay pot.", question: "What is the most likely historical interpretation of this evidence?", options: ["The presence of these bones indicates a severe rodent infestation in the local market", "They specifically bred and consumed these small rodents as a high-status delicacy", "These animals were kept as sacred pets and buried within the homes of the wealthy", "The rodents entered the jars seeking food and became trapped during a flood event"], correct: 1 },

      { id: 'rm_13', name: "Wax Tablet", type: "written", discoveryMethod: "Found in a waterlogged anaerobic environment that preserved the wood.", clue: "A wooden board with a layer of wax, scratched with a stylus.", question: "What is the most likely historical interpretation of this evidence?", options: ["They utilized reusable tools for temporary notes, educational practice, or business", "This device was a specialized light source used in dark library and study environments", "The wax was used to seal important legal documents rather than for direct writing", "It served as a protective cover for more expensive and fragile papyrus documents"], correct: 0 },
      { id: 'rm_14', name: "Monumental Inscription", type: "written", discoveryMethod: "Documented using photogrammetry on a public building.", clue: "Large Latin letters carved deeply into a marble slab.", question: "What is the most likely historical interpretation of this evidence?", options: ["These carvings were a specialized form of code used to track government taxes", "Public literacy was widespread enough to justify monumental civic announcements", "The letters were primarily decorative and few people could actually read them", "This slab served as a specialized weight used for testing the strength of buildings"], correct: 1 },
      { id: 'rm_15', name: "Carbonized Scroll", type: "written", discoveryMethod: "Scanned using a particle accelerator to read the text without unrolling.", clue: "A papyrus scroll burnt to charcoal by a volcano.", question: "What is the most likely historical interpretation of this evidence?", options: ["They maintained extensive libraries of philosophy, literature, and official records", "The scroll was used as a high-value fire starter during a ritual temple ceremony", "This object was a specialized container used for storing expensive medicinal herbs", "The papyrus was imported solely for the purpose of making durable fishing nets"], correct: 0 }
    ]
  },
  {
    id: 'china',
    name: 'The Eastern Dynasties',
    civilization: 'Ancient China',
    historicalContext: 'Ancient Chinese archaeology spans millennia of dynastic rule. Discoveries like the Oracle Bones and Terracotta Army reveal a society with early writing, sophisticated metallurgy, and complex spiritual beliefs.',
    evidence: [
      { id: 'ch_1', name: "Bronze Ding", type: "objects", discoveryMethod: "Unearthed with a trowel from an elite burial pit.", clue: "A massive, heavy bronze cauldron standing on three legs.", question: "What is the most likely historical interpretation of this evidence?", options: ["These vessels were used for everyday cooking by peasant families in rural villages", "They served as symbols of high political power and were used in sacred state rituals", "They were used primarily as specialized storage containers for surplus grain reserves", "The ding was a specialized musical instrument played during major imperial festivals"], correct: 1 },
      { id: 'ch_2', name: "Terracotta Fragment", type: "objects", discoveryMethod: "Excavated from a massive trench using brushes and dental tools.", clue: "A piece of a life-sized clay soldier.", question: "What is the most likely historical interpretation of this evidence?", options: ["They believed the Emperor required a literal army to protect his spirit in the afterlife", "These statues were intended to represent the diverse ethnic groups within the empire", "They served as specialized building supports for the massive roof of the burial complex", "The fragments belong to a set of monumental sculptures designed for a public plaza"], correct: 0, image: "/museum/china_terracotta.png" },
      { id: 'ch_3', name: "Jade Ornament", type: "objects", discoveryMethod: "Found using a fine sieve in a burial chamber.", clue: "A beautifully carved green stone disc.", question: "What is the most likely historical interpretation of this evidence?", options: ["Jade was a specialized material used only for the production of advanced cutting tools", "The stone held supreme spiritual value and represented purity, status, and immortality", "These discs were utilized as a standardized form of high-value currency for trade", "The ornaments were used as specialized weights for securing expensive silk burial shrouds"], correct: 1, image: "/museum/china_jade_dragon.png" },

      { id: 'ch_4', name: "Chariot Horse Skeletons", type: "remains", discoveryMethod: "Uncovered in a sacrificial pit alongside wooden chariot remains.", clue: "The bones of several horses buried in formation.", question: "What is the most likely historical interpretation of this evidence?", options: ["The horses died during a sudden and catastrophic outbreak of a regional equine disease", "They practiced ritualized animal sacrifice to accompany elite members into the afterlife", "These animals were buried together to mark the location of a major military victory", "The pit was a specialized disposal area for horses that were too old for agricultural work"], correct: 1, image: "/museum/china_horse_skeletons.png", rationale: "In the Shang and Zhou dynasties, horses and chariots were buried in sacrificial pits near elite tombs. This reflected the status of the deceased and their perceived need for military transport in the afterlife." },
      { id: 'ch_5', name: "Silk-Wrapped Bones", type: "remains", discoveryMethod: "Analyzed under a microscope to identify the organic fibers.", clue: "Human remains showing microscopic traces of woven silk threads.", question: "What is the most likely historical interpretation of this evidence?", options: ["The silk traces are a result of natural spider activity within the burial chamber", "They used silk as a specialized medicinal wrap to prevent the decay of the physical body", "They invented and utilized advanced silk weaving technology for high-status garments", "Silk was an expensive import used solely for the decoration of sacred religious icons"], correct: 2 },
      { id: 'ch_6', name: "Laborer Skeletons", type: "remains", discoveryMethod: "Discovered buried en masse within the foundation of a large wall.", clue: "Skeletons showing extreme physical stress and malnutrition.", question: "What is the most likely historical interpretation of this evidence?", options: ["These individuals were specialized athletes who died during a major imperial competition", "The remains belong to a group of soldiers who died defending the wall during a siege", "They were buried here as part of a ritual ceremony to ensure the strength of the wall", "Massive building projects relied on the intensive, forced labor of the peasant population"], correct: 3 },

      { id: 'ch_7', name: "Rammed Earth Wall", type: "structures", discoveryMethod: "Surveyed using GPS and soil core samples.", clue: "A massive defensive barrier made of highly compacted dirt.", question: "What is the most likely historical interpretation of this evidence?", options: ["They possessed a strong central authority capable of mobilizing labor for defense", "This wall was built primarily as a flood control system for the surrounding farmland", "It served as a boundary marker to separate the lands of different agricultural clans", "The structure was used as a raised roadway to facilitate the rapid movement of armies"], correct: 0 },
      { id: 'ch_8', name: "Wooden Pagoda Foundation", type: "structures", discoveryMethod: "Excavated using large trowels to reveal the stone bases of timber pillars.", clue: "A square foundation designed to support a multi-story wooden tower.", question: "What is the most likely historical interpretation of this evidence?", options: ["The foundation was designed to support a massive wooden statue of a local deity", "They utilized advanced timber architecture with complex joinery for vertical growth", "It served as a specialized lookout tower for monitoring potential fires in the city", "The stone bases were intended to protect the wooden pillars from burrowing animals"], correct: 1 },
      { id: 'ch_9', name: "Ceramic Kiln", type: "structures", discoveryMethod: "Identified by a massive concentration of ash and broken pottery.", clue: "A large, dragon-shaped oven built into a hillside.", question: "What is the most likely historical interpretation of this evidence?", options: ["The oven was used for the high-temperature baking of specialized ceremonial bread", "They had established industrial-scale production of high-quality ceramics and porcelain", "It served as a specialized communal heater for the residents of a nearby village", "The structure was a specialized furnace for the mass-production of bronze weapons"], correct: 1 },

      { id: 'ch_10', name: "Rice Grains", type: "environment", discoveryMethod: "Recovered via flotation from a waterlogged pit.", clue: "Carbonized grains of domesticated rice.", question: "What is the most likely historical interpretation of this evidence?", options: ["They relied on intensive wet-field rice agriculture as a foundational food source", "Rice was a specialized crop grown only for the production of ceremonial wine", "The grains were imported from distant southern regions and were a luxury item", "They utilized these grains as a form of payment for local government officials"], correct: 0 },
      { id: 'ch_11', name: "Mulberry Leaves", type: "environment", discoveryMethod: "Found perfectly preserved in a sealed, anaerobic jar.", clue: "Leaves specifically from the White Mulberry tree.", question: "What is the most likely historical interpretation of this evidence?", options: ["These leaves were gathered and dried for use as a specialized medicinal tea", "They systematically cultivated mulberries to sustain silkworms for silk production", "The leaves were used as a specialized building material for temporary shelters", "They were used as a primary food source for domesticated livestock during the winter"], correct: 1 },
      { id: 'ch_12', name: "Millet Seeds", type: "environment", discoveryMethod: "Sieved from an ancient hearth in the northern region.", clue: "Tiny seeds of a drought-resistant grain.", question: "What is the most likely historical interpretation of this evidence?", options: ["The seeds were used primarily as a specialized form of bird feed for palace pets", "The northern climate required the systematic farming of hardy, drought-resistant crops", "They utilized these seeds as a specialized ingredient in high-strength concrete", "Millet was a wild-growing weed that was accidentally gathered along with other grains"], correct: 1 },

      { id: 'ch_13', name: "Oracle Bone", type: "written", discoveryMethod: "Carefully unearthed and deciphered by linguistic experts.", clue: "A turtle shell cracked by fire, covered in ancient characters.", question: "What is the most likely historical interpretation of this evidence?", options: ["Writing originated and evolved as a specialized tool for divination and prophecy", "These shells were used as a specialized form of currency for high-value trade", "The characters represent a specialized code used by merchants to track inventory", "This object was a ceremonial plaque used to honor successful military commanders"], correct: 0 },
      { id: 'ch_14', name: "Bamboo Slips", type: "written", discoveryMethod: "Excavated from a dry tomb, unrolled with extreme care.", clue: "Strips of bamboo tied together, written on vertically with ink.", question: "What is the most likely historical interpretation of this evidence?", options: ["The slips were used as specialized building materials for high-status furniture", "This was the primary medium for recording literature, laws, and official records", "They utilized bamboo strips as a specialized form of armor for light infantry", "The writing was intended as a series of labels for identifying medicinal herbs"], correct: 1 },
      { id: 'ch_15', name: "Bronze Inscription", type: "written", discoveryMethod: "Cleaned using chemical solvents in a conservation lab.", clue: "Characters cast into the inside of a ritual bronze vessel.", question: "What is the most likely historical interpretation of this evidence?", options: ["They used these vessels to record significant historical events, treaties, or honors", "The inscriptions were secret religious codes that were intended to be hidden from view", "They utilized these characters as specialized instructions for the use of the vessel", "The writing was a specialized artist signature used to identify the creator of the work"], correct: 0 }
    ]
  }
];

export const RED_HERRINGS = [
  { 
    id: 'rh_1', 
    name: "Aluminium Soda Can", 
    type: "objects", 
    isRedHerring: true,
    discoveryMethod: "Found in the topsoil layer during initial clearing.", 
    clue: "A crushed metal cylinder with bright red paint and a pull-tab.", 
    question: "What is the most likely archaeological interpretation of this evidence?", 
    options: ["The site was inhabited by a previously unknown high-technology civilization", "This item represents modern 'contamination' and indicates the site has been disturbed", "The object was likely a specialized ritual vessel used for liquid offerings", "It was traded into the region by a distant and highly advanced nomadic group"], 
    correct: 1 
  },
  { 
    id: 'rh_2', 
    name: "Plastic Water Bottle", 
    type: "objects", 
    isRedHerring: true,
    discoveryMethod: "Discovered near a modern animal burrow that dug into the site.", 
    clue: "A clear, flexible container made of synthetic polymers.", 
    question: "Why is this modern synthetic item located within an ancient soil layer?", 
    options: ["Ancient societies had developed sophisticated polymer chemistry and manufacturing", "It is 'intrusive evidence' moved into the layer by animal activity or soil erosion", "The bottle was used as a specialized water storage device during the ancient period", "It was intentionally buried as a time capsule for future generations to discover"], 
    correct: 1 
  },
  { 
    id: 'rh_3', 
    name: "Modern 2-Dollar Coin", 
    type: "objects", 
    isRedHerring: true,
    discoveryMethod: "Found using a metal detector in the backfill pile.", 
    clue: "A small gold-colored disc with the date '2024' stamped on it.", 
    question: "What is the primary archaeological significance of this specific discovery?", 
    options: ["The date confirms that the entire archaeological site was constructed in 2024", "It is a modern loss and provides no useful information about the ancient context", "Ancient civilizations had a complex trading relationship with modern nations", "The coin was used as a specialized weight for precision scales in the ancient market"], 
    correct: 1 
  }
];
